

export const GET_JOBS_FAILURE = "GET_JOBS_FAILURE";
export const GET_JOBS_REQUEST = "GET_JOBS_REQUEST";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";

export const GET_APPLY_JOB_FAILURE = "GET_APPLY_JOB_FAILURE";
export const GET_APPLY_JOB_REQUEST = "GET_APPLY_JOB_REQUEST";
export const GET_APPLY_JOB_SUCCESS = "GET_APPLY_JOB_SUCCESS";